version: '3.4'
services:
  mvc_sample:
    image: osscjpdevinfra/mvcsample:MVCSampleOnDocker
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - UseUrl=http://0.0.0.0:5000/
      - RedisConfig=redis
      - RedisInstanceName=redis
      - ConnectionString_SQL=Data Source=sqlserver;Initial Catalog=Northwind;User ID=sa;Password=seigi@123;
      - ConnectionString_MCN=Server=mysql;Database=test;User Id=root;Password=seigi@123;
      - ConnectionString_NPS=HOST=postgres;DATABASE=postgres;USER ID=postgres;PASSWORD=seigi@123;
      - JwkSetUri=http://multipurposeauthsitecore:5000/jwkcerts/
      - SpRp_AuthRequestUri=http://localhost:44300/authorize
      - SpRp_TokenRequestUri=http://multipurposeauthsitecore:5000/token
      - SpRp_UserInfoUri=http://multipurposeauthsitecore:5000/userinfo
      - SpRp_RedirectUri=http://localhost:58496/Home/OAuth2AuthorizationCodeGrantClient
    ports:
      - "58496:5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - common_link

networks:
  common_link:
    external: true